### PR TITLE
Fix compilation in bytecode mode

### PR DESCRIPTION
**Pull request by mseri**
This should solve the issue in https://github.com/ocaml/opam-repository/pull/25033

### CODE REVIEW

**Comment by hackwaly** [comment]
I merged it. /cc @sim642

**Comment by mseri** [comment]
Do you want to update the release or I can merge that with the conflict with bytecode compiler?

**Comment by hackwaly** [comment]
> Do you want to update the release or I can merge that with the conflict with bytecode compiler?

Thank you! Your patch could be released with next release.

**Comment by sim642** [comment]
It shouldn't be the same release because 1.3.0 is already in our GitHub releases etc. I can release 1.3.1 with this soon too.

**Comment by hackwaly** [comment]
> It shouldn't be the same release because 1.3.0 is already in our GitHub releases etc. I can release 1.3.1 with this soon too.

Could you release 1.3.1? I've already forgotten how to use dune-release.

**Comment by sim642** [comment]
This doesn't seem to really help: https://github.com/ocaml/opam-repository/pull/25063 fails with

```
#=== ERROR while compiling earlybird.1.3.1 ====================================#
# context              2.2.0~alpha4~dev | linux/arm32 | ocaml-base-compiler.5.1.1 | pinned(https://github.com/hackwaly/ocamlearlybird/releases/download/1.3.1/earlybird-1.3.1.tbz)
# path                 ~/.opam/5.1/.opam-switch/build/earlybird.1.3.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p earlybird -j 79 @install
# exit-code            1
# env-file             ~/.opam/log/earlybird-7-2e1bf8.env
# output-file          ~/.opam/log/earlybird-7-2e1bf8.out
### output ###
# File "src/main/dune", line 3, characters 7-11:
# 3 |  (name main)
#            ^^^^
# Error: No rule found for src/main/main.exe
```
It's the same problem, just from a slightly different place.

**Comment by mseri** [comment]
Mmh, very strange. I'll try to look into it. Unfortunately I cannot do it for some time still.

**Comment by sim642** [comment]
I suspect the reason is this line:
https://github.com/hackwaly/ocamlearlybird/blob/63f0a3fbc2fc0af388f984da1d447eefa708c39b/src/main/dune#L4

In [dune's linking modes](https://dune.readthedocs.io/en/stable/dune-files.html#linking-modes), this demands both native and bytecode binaries, but that might not be necessary. The default `exe` might already do the right thing: produce an `exe`, which might be native or which might be a bytecode one.

**Pull request merged**
